
[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[colors.cursor]
cursor = "#839496"
text = "#002b36"

[colors.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[colors.primary]
background = "#002B36"
foreground = "#839496"

[env]
TERM = "screen-256color"

[font]
size = 11
#use_thin_strokes = false

[font.bold]
family = "Inconsolata-g for Powerline"
style = "g"

[font.italic]
family = "Inconsolata-g for Powerline"
style = "g"

[font.normal]
family = "Inconsolata-g for Powerline"
style = "g"

[mouse]
hide_when_typing = true

[scrolling]
history = 50000
multiplier = 4

[window]
decorations = "full"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 10
y = 10
